version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - '3000:3000'

  upload-api:
    build: ./apps/upload-api
    ports:
      - '3010:3010'
    volumes:
      - ./apps/upload-api/uploads:/app/uploads

  db:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
