version: '3.9'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - '3000:3000'
    networks:
      - app_network
    # volumes:
    #   - ./apps/web:/app

  upload-api:
    container_name: upload-api
    build: ./apps/upload-api
    # build:
    #   context: .
    #   dockerfile: ./apps/upload-api/Dockerfile
    ports:
      - '3010:3010'
    volumes:
      - ./apps/upload-api/uploads:/app/uploads
    networks:
      - app_network

networks:
  app_network:
    external: true
