version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - '3000:3000'

  upload-api:
    build: ./apps/upload-api
    ports:
      - '3010:3010'
    volumes:
      - ./apps/upload-api/uploads:/app/uploads
