"""add logic to faceto AI

Revision ID: 8f8bc2f414e8
Revises: e44150d0e6cb
Create Date: 2023-08-08 16:36:23.531250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f8bc2f414e8'
down_revision = 'e44150d0e6cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('enable_video_interaction', sa.Boolean(), nullable=True))
    op.add_column('models', sa.Column('opening_remarks', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'opening_remarks')
    op.drop_column('models', 'enable_video_interaction')
    # ### end Alembic commands ###
