"""chain video interaction

Revision ID: 9987a2eb7d9e
Revises: 2f0505801d0d
Create Date: 2023-11-17 11:04:17.310455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9987a2eb7d9e'
down_revision = '2f0505801d0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
