"""create retrieval column

Revision ID: bc337f760cbb
Revises: b5321c6b9328
Create Date: 2023-08-01 18:13:23.177337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc337f760cbb'
down_revision = 'b5321c6b9328'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backend_datasets', sa.Column('retrieval', sa.JSON(), nullable=True))
    op.drop_column('backend_models', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backend_models', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('backend_datasets', 'retrieval')
    # ### end Alembic commands ###
