"""create sessionstate table, change table name

Revision ID: e44150d0e6cb
Revises: bc337f760cbb
Create Date: 2023-08-02 14:56:07.639912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e44150d0e6cb'
down_revision = 'bc337f760cbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('retrieval', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chains', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_state',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('backend_datasets')
    op.drop_table('backend_models')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backend_models',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('chains', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='backend_models_pkey')
    )
    op.create_table('backend_datasets',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('documents', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('retrieval', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='backend_datasets_pkey')
    )
    op.drop_table('session_state')
    op.drop_table('models')
    op.drop_table('datasets')
    # ### end Alembic commands ###
