# Dockerfile.base

FROM python:3.11-slim

WORKDIR /base
RUN apt update
RUN apt install -y unoconv
RUN apt install -y libreoffice
RUN apt install -y python3-uno
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
